version: '3.8'

services:
  harusame-ui-demo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
